version: '3'

services:

  gateway:
    container_name: gateway
    image: teamcity-dd-gateway:latest
    restart: unless-stopped
    networks:
      dmz:
        ipv4_address: ${GATEWAY_IP}
    ports:
      - ${EXT_PORT}:${INT_PORT}
    environment:
      - CLIENT=http://${CLIENT_IP}:${INT_PORT}

  client:
    container_name: client
    image: teamcity-dd-client:latest
    restart: unless-stopped
    networks:
      dmz:
        ipv4_address: ${CLIENT_IP}
    expose:
      - ${INT_PORT}

  authentication:
    container_name: authentication
    image: teamcity-dd-authentication:latest
    restart: unless-stopped
    networks:
      dmz:
        ipv4_address: ${AUTHENTICATION_IP}
    expose:
      - ${INT_PORT}
    depends_on:
      - authentication_db

  # === Databases === #
  authentication_db:
    container_name: authentication_db
    image: mysql:latest
    restart: always
    networks:
      dmz:
        ipv4_address: ${AUTHENTICATION_DB_IP}
    volumes:
      - "authentication_config:/etc/mysql/conf.d/config-file.cnf"
      - "authentication_data:/var/lib/mysql:rw"

    expose:
      - ${MYSQL_PORT}
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: auth
      MYSQL_TCP_PORT: ${MYSQL_PORT}

volumes:
  authentication_data:
  authentication_config:

networks:
  dmz:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
