version: '3'

services:

  client:
    container_name: client
    image: teamcity-dd-client:latest
    restart: unless-stopped
    networks:
      - dd-net
    ports:
      - ${EXT_PORT}:${INT_PORT}
    depends_on:
      - authentication_db
      - projects_db

  # === Databases === #
  authentication_db:
    container_name: authentication_db
    image: mysql:latest
    restart: always
    networks:
      - dd-net
    volumes:
      - "authentication_config:/etc/mysql/conf.d/config-file.cnf"
      - "authentication_data:/var/lib/mysql:rw"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: auth
      MYSQL_TCP_PORT: ${MYSQL_PORT}

  projects_db:
    container_name: projects_db
    image: mongo:4.4.18
    restart: always
    networks:
      - dd-net
    volumes:
      - "projects_data:/data/db"
      - "projects_config:/data/configdb"
    expose:
      - ${MONGO_PORT}
    environment:
      MONGO_INITDB_DATABASE: projects

#  translation_db:
#    container_name: translation_db
#    image: mongo:4.4.18
#    restart: always
#    networks:
#      - dd-net
#    volumes:
#      - "translations_data:/data/db"
#      - "translations_config:/data/configdb"
#    expose:
#      - ${MONGO_PORT}
#    environment:
#      MONGO_INITDB_DATABASE: translations

volumes:
  authentication_data:
  authentication_config:
  projects_data:
  projects_config:

networks:
  dd-net:
