version: '3'

services:

  geoserver:
    ports:
      - "9090:8080"

  # === Databases === #
  authentication_db:
    ports:
      - "3307:3306"

  projects_db:
    ports:
      - "27018:27017"

  geoserver_db:
    ports:
      - "5432:5432"


