version: '3'

services:

  client:
    container_name: client
    image: teamcity-dd-client:latest
    restart: unless-stopped
    networks:
      - dd-net
    ports:
      - ${EXT_PORT}:${INT_PORT}
    depends_on:
      - authentication_db
      - projects_db

  geoserver:
    container_name: geoserver
    image: docker.osgeo.org/geoserver:2.21.1
    restart: unless-stopped
    networks:
      - dd-net
    expose:
      - ${GEO_PORT}
    volumes:
      - "geoserver_data:/opt/geoserver_data/:Z"
    depends_on:
      - geoserver_db

  # === Databases === #
  authentication_db:
    container_name: authentication_db
    image: mysql:latest
    restart: always
    networks:
      - dd-net
    volumes:
      - "authentication_config:/etc/mysql/conf.d/config-file.cnf"
      - "authentication_data:/var/lib/mysql:rw"
    expose:
      - ${MYSQL_PORT}
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: auth
      MYSQL_TCP_PORT: ${MYSQL_PORT}

  projects_db:
    container_name: projects_db
    image: mongo:4.4.18
    restart: always
    networks:
      - dd-net
    volumes:
      - "projects_data:/data/db"
      - "projects_config:/data/configdb"
    expose:
      - ${MONGO_PORT}
    environment:
      MONGO_INITDB_DATABASE: projects

  geoserver_db:
    container_name: geoserver_db
    image: postgis/postgis:15-3.3
    restart: always
    networks:
      - dd-net
    volumes:
      - "postgis_data:/var/lib/postgresql/data"
      - "postgis_config:/etc/postgresql/postgresql.conf"
    expose:
      - ${POSTGIS_PORT}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PW}
      POSTGRES_DB: geodata

#  translation_db:
#    container_name: translation_db
#    image: mongo:4.4.18
#    restart: always
#    networks:
#      - dd-net
#    volumes:
#      - "translations_data:/data/db"
#      - "translations_config:/data/configdb"
#    expose:
#      - ${MONGO_PORT}
#    environment:
#      MONGO_INITDB_DATABASE: translations

volumes:
  authentication_data:
  authentication_config:
  projects_data:
  projects_config:
  postgis_data:
  postgis_config:
  geoserver_data:

networks:
  dd-net:
