version: '3'

services:

  gateway:
    container_name: gateway
    image: teamcity-dd-gateway:latest
    restart: unless-stopped
    networks:
      dmz:
        ipv4_address: ${GATEWAY_IP}
    ports:
      - ${EXT_PORT}:${INT_PORT}
    environment:
      - CLIENT=http://${CLIENT_IP}:${INT_PORT}

  client:
    container_name: client
    image: teamcity-dd-client:latest
    restart: unless-stopped
    networks:
      dmz:
        ipv4_address: ${CLIENT_IP}
    expose:
      - ${INT_PORT}

  # === Databases === #
  authentication_db:
    container_name: authentication_db
    image: mysql:latest
    restart: always
    networks:
      dmz:
        ipv4_address: ${AUTHENTICATION_DB_IP}
    expose:
      - ${MYSQL_PORT}
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: auth
      MYSQL_TCP_PORT: ${MYSQL_PORT}

networks:
  dmz:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
