openapi: 3.0.0

info:
  title: Data Dagger API
  description: ""
  version: 0.1.9

paths:
  /api/auth/login:
    post:
      tags:
        - "Authentication"
      summary: "User Login"
      description: "Stateless user login with JWT and refresh token cookies"
      parameters:
        - in: body
          schema:
            name: user
            type: object
            required:
              - email
              - password
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        '200':
          description: "OK: JWT cookie and RefreshToken cookie are attached to response."
        '400':
          description: "Bad Request: email and/or password is missing."
        '401':
          description: "Unauthorized: Credentials are incorrect or user is disabled."
